# Generated by Django 4.1.1 on 2022-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('digital art', 'Digital Art'), ('modeling', 'Modeling')], default='programming', max_length=15)),
            ],
        ),
    ]
